---
- name: read variables from prompt
  hosts: local
  connection: local
  vars_prompt:
    - name: username
      prompt: What is your username?
      private: false
    - name: password
      prompt: What is your password?
      private: true
  tasks:
    - name: print the values
      ansible.builtin.debug:
        msg: "User name is: {{ username}}, password is: {{ password }}"