---
- name: read variables from prompt
  hosts: local
  connection: local
  vars_prompt:
    - name: username
      prompt: What is your username?
      private: false
  tasks:
    - name: print the values
      ansible.builtin.debug:
        msg: "User name is: {{ username   }}"