---
- name: default function 
  hosts: local
  connection: local
  tasks: 
    - name: print the name with default
      ansible.builtin.debug:
        msg: "Default variable name is: {{ name | default('hari') }}"