---
- name: default function 
  hosts: local
  connection: local
  vars:
   technologies: Ansible,AWS,Terraform
  tasks: 
    - name: print the name with default
      ansible.builtin.debug:
        msg: "Default variable name is: {{ name | default('hari') }}"
    - name: print the list values
      ansible.builtin.debug:
        msg: "List values are: {{ technologies | split(',')}}" # convert string to a list by using split fucntion and convert to a list
        # output => ["Ansible ,"AWS", "Terraform"]
        # # listjojo => [ "jojo", "is", "a" ]
        # listjojo: "{{ 'jojo is a' | split }}"

        # # listjojocomma => [ "jojo is", " a" ]
        # listjojocomma: "{{ 'jojo is, a' | split(',') }}"