---
- name: default function 
  hosts: local
  connection: local
  vars:
   technologies: Ansible,AWS,Terraform # string
   #dictonary = map
   maptolist: 
    application: Payment
    environment: Dev
  tasks: 
    - name: print the name with default
      ansible.builtin.debug:
        msg: "Default variable name is: {{ name | default('hari') }}"
    - name: print the list values
      ansible.builtin.debug:
        msg: "List values are: {{ technologies | split(',')}}" # convert string to a list by using split fucntion and convert to a list
        # output => ['Ansible' ,'AWS', 'Terraform']
    - name: print the map to list values
      ansible.builtin.debug:
        msg: "MaptoList values are: {{ maptolist | dict2items }}"